### PR TITLE
store Declarators in CommonGroup

### PR DESCRIPTION
**Pull request by raehik**
* [ ] parser rule naming (bit all over the place)
  * [x] investigate/discuss impact for analysis, common block elimination

### CODE REVIEW

**Comment by raehik** [comment]
Somehow, I've broken an array initializer test for the F77 parser. The S/R conflicts went up from 1 to 4. Think it's due to declarator syntax allowing initializers. I specifically avoided that in some of the other parsers, but apparently works differently for F77 (and maybe F66).

**Comment by raehik** [comment]
OK, so F66 doesn't have initializers in declarators, and the COMMON parsing in the other parsers uses explicit non-initializing declarators. This is prepared for merge, but I want to hold off until I've discussed the related CamFort change @ https://github.com/camfort/camfort/pull/136 with @dorchard .

**Comment by dorchard** [comment]
This looks a good change.

**Comment by raehik** [comment]
This is an AST change, but it has minimal impact on fortran-src & CamFort codebases. I'll clean up the new parser rules, add a changelog entry and merge.

**Pull request merged**
