### PR TITLE
Allow selection of post-parse AST transformations

### PR DESCRIPTION
**Pull request by raehik**
Centralize default transformations and export more parsers (currently for Fortran 66 only).

### CODE REVIEW

**Comment by raehik** [comment]
@dorchard There's some documentation and work on the other parsers remaining, but the gist of the change can be seen in the [Fortran 66 parser](https://github.com/camfort/fortran-src/pull/138/files#diff-5bf082a1f3dc617089a2bf85ba63dded214f4cd0bc3b5eacb457625197a4684dR512).

Adding in 3 transformation options onto the 2 modfile options gives a total of 6 choices for parsers, which I think is the limit for what we want to export. (I'll make it clear in the docs that `xNoTrans` and `x` are aliases for `xWithTrans []` and `xWithTrans defaultTransformations`.) Is this the right direction?

**Comment by dorchard** [comment]
This looks to me. (as discussed with @raehik perhaps s/Trans/Transform for clarity) if @mrd  is happy then we can apply this idea to all the other parsers.

**Comment by mrd** [comment]
> This looks to me. (as discussed with @raehik perhaps s/Trans/Transform for clarity) if @mrd is happy then we can apply this idea to all the other parsers.

Fine by me - maybe unnecessary to have *NoTrans functions as the use case is limited and easily substituted.

**Comment by raehik** [comment]
Agreed on removing the `*NoTransforms` functions, the derivation should be obvious for any end user.

New parsers are named with the scheme `*WithTransforms`, because using singular there feels inappropriate for a list.

I did the association list -> function refactors I mentioned, it makes an error case (no parser for given Fortran version) a lot clearer. @mrd @dorchard thoughts?

**Comment by dorchard** [comment]
Looking good!

**Comment by raehik** [comment]
Added a Haddock note on parser naming so the new functions won't get lost -- merging now

**Pull request merged**
